FROM demo:ci

ENV RAILS_ENV staging
ENV RAILS_SERVE_STATIC_FILES true 

WORKDIR /usr/src/app

RUN bundle install --deployment
RUN RAILS_ENV=staging rake assets:precompile

CMD ["bin/bundle", "exec", "unicorn", "-p", "3000", "-E", "staging"]

