# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgres
  pool: 5
  timeout: 5000

development: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: postgres
  username: postgres
  password:
  host: db

test:
  <<: *default
  host: demo_db
  database: myapp_test

staging:
  <<: *default
  host: demo_db_staging
  database: myapp_staging

production:
  <<: *default
  host: demo_db_production
  database: myapp_production
